-- Ensure TAX_CLASS table has AUTO_INCREMENT
ALTER TABLE TAX_CLASS MODIFY COLUMN TAX_CLASS_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY;

-- Ensure TAX_RATE table has AUTO_INCREMENT
ALTER TABLE TAX_RATE MODIFY COLUMN TAX_RATE_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY;
